name: Validate config schema

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - 'config.js'
  workflow_dispatch:

jobs:
  publish:
    name: Validate Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - name: Validate config
        run: node src/validateConfigs.js